### ISSUE TITLE
Fails to load games after moving games

### ISSUE THREAD

**Issue by Rsl1122** [Rsl1122/ROM-tools#1]
```
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.djrapitops.rom.backend.database.dao.GamesDAO.get(GamesDAO.java:47)
        at com.djrapitops.rom.backend.database.dao.GamesDAO.get(GamesDAO.java:25)
        at com.djrapitops.rom.backend.database.SQLDatabase.fetch(SQLDatabase.java:32)
        at com.djrapitops.rom.backend.cache.GameCache.lambda$fetch$0(GameCache.java:35)
        at com.djrapitops.rom.backend.cache.GameCache.getOrFetch(GameCache.java:49)
        at com.djrapitops.rom.backend.cache.GameCache.fetch(GameCache.java:35)
        at com.djrapitops.rom.backend.Operation.get(Operation.java:27)
        at com.djrapitops.rom.backend.processes.GameProcesses.loadGames(GameProcesses.java:29)
        ... 4 more
```

Temp fix: Delete games.db

**Comment by Rsl1122** [comment]
Not fixed but hide.
